version: '3'

services:
  registler:
    build:
      context: .
      x-bake:
        tags:
          - ghcr.io/${GITHUB_REPOSITORY}:latest
          - ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA}
        platforms:
          - linux/amd64
          - linux/arm64
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./cloudflared.pem:/cloudflared.pem
    # ports:
    #   - 6000:5000
