version: 0.1
log:
  accesslog:
    disabled: true # todo
  level: info
  formatter: text
http:
  addr: 0.0.0.0:5000
  relativeurls: false # TODO: ??
  draintimeout: 10s
health:
  storagedriver:
    enabled: false
storage:
  delete:
    enabled: true
  redirect:
    disable: false # TODO: ?
  #  cache:
  #    blobdescriptor: redis
  maintenance:
    uploadpurging:
      enabled: true
      age: 1h
      interval: 1h # TODO
      dryrun: false
